import os
import logging
from typing import List, Dict, Any, Optional
import chromadb
from chromadb.api.types import EmbeddingFunction

# Set up centralized logging
logger = logging.getLogger(__name__)

class VectorStoreService:
    """
    Service wrapper for managing vector database operations using ChromaDB.
    Handles collection lifecycles, document metadata ingestion, and semantic search.
    """

    def __init__(self) -> None:
        """Initializes the persistent ChromaDB client using environment configurations."""
        self.db_path: str = os.getenv("VECTOR_DB_PATH", "./chroma_db")
        try:
            self.client = chromadb.PersistentClient(path=self.db_path)
            logger.info(f"VectorStoreService successfully connected to storage at: {self.db_path}")
        except Exception as e:
            logger.error(f"Failed to initialize Vector Store Client: {str(e)}")
            raise e

    def _get_or_create_collection(self, collection_name: str, embedding_function: Optional[EmbeddingFunction] = None) -> Any:
        """
        Internal helper to fetch or dynamically spin up a collection.
        
        Args:
            collection_name (str): The identifier for the collection/index.
            embedding_function (Optional[EmbeddingFunction]): Optional custom model mapping function.
        """
        try:
            return self.client.get_or_create_collection(
                name=collection_name, 
                embedding_function=embedding_function
            )
        except Exception as e:
            logger.error(f"Error accessing collection '{collection_name}': {str(e)}")
            raise e

    def upsert_documents(
        self, 
        collection_name: str, 
        ids: List[str], 
        embeddings: List[List[float]], 
        documents: List[str], 
        metadatas: Optional[List[Dict[str, Any]]] = None
    ) -> bool:
        """
        Inserts or updates vector embeddings along with text chunks and relevant metadata.
        
        Args:
            collection_name (str): Destination collection.
            ids (List[str]): Unique identifiers for each document chunk.
            embeddings (List[List[float]]): Vector array representation generated by your embedding model.
            documents (List[str]): Plain text strings representing raw chunks.
            metadatas (Optional[List[Dict[str, Any]]]): Key/Value pairs mapping source targets (e.g., file name, page #).
        """
        try:
            collection = self._get_or_create_collection(collection_name)
            collection.upsert(
                ids=ids,
                embeddings=embeddings,
                documents=documents,
                metadatas=metadatas
            )
            logger.info(f"Successfully upserted {len(ids)} chunks into vector collection: '{collection_name}'")
            return True
        except Exception as e:
            logger.error(f"Failed to upsert records into vector collection '{collection_name}': {str(e)}")
            return False

    def query_similarity(
        self, 
        collection_name: str, 
        query_embeddings: List[List[float]], 
        top_k: int = 4
    ) -> Dict[str, Any]:
        """
        Executes a semantic similarity search based on a query vector.
        
        Args:
            collection_name (str): Collection target to search within.
            query_embeddings (List[List[float]]): Embeddings of the user's plain text query.
            top_k (int): Limit configuration specifying the max count of relevant document chunks to pull back.
        """
        try:
            collection = self._get_or_create_collection(collection_name)
            results = collection.query(
                query_embeddings=query_embeddings,
                n_results=top_k
            )
            logger.info(f"Similarity query completed for collection '{collection_name}' fetching top_{top_k} vectors.")
            return results
        except Exception as e:
            logger.error(f"Error executing similarity search on collection '{collection_name}': {str(e)}")
            return {"ids": [], "distances": [], "metadatas": [], "documents": []}

    def delete_collection(self, collection_name: str) -> bool:
        """
        Permanently purges a collection from memory and disk. Use with caution.
        
        Args:
            collection_name (str): The identifier targeted for deletion.
        """
        try:
            self.client.delete_collection(name=collection_name)
            logger.info(f"Collection '{collection_name}' successfully removed from vector storage.")
            return True
        except Exception as e:
            logger.warning(f"Could not delete collection '{collection_name}' (it may not exist): {str(e)}")
            return False